# Generated by Django 3.0.10 on 2020-09-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_post', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('post_ower', models.TextField()),
            ],
        ),
    ]
